library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(readr)
library(dplyr)
library(tidyr)
library(httr)
require(rvest)
require(XML)
require(stringr)
library(ggplot2)
library(ggdendro)
library(plotly)

options(gsubfn.engine="R")

source("lib/uvozi.zemljevid.r", encoding="UTF-8")